name: nix build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - main
      - release

jobs:
  build:
    name: Build cabal-audit
    runs-on: self-hosted
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            system-features = nixos-test benchmark big-parallel kvm
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check flake 
        run: | 
          nix -Lv flake check

      - name: Build cabal-audit
        run: |
          nix -Lv build

      - name: Build cabal-audit static
        run: |
          nix -Lv build .#cabal-audit-static -o result-static

      - name: Create release artifacts
        run: | 
          mkdir -p artifacts

          cp result-static/bin/cabal-audit artifacts
          chmod +x artifacts/cabal-audit

      - name: Upload static cabal-audit exe
        uses: actions/upload-artifact@v4
        with:
          name: cabal-audit
          path: artifacts/cabal-audit

      - name: Release nightly cabal-audit exe
        if: github.ref == 'refs/heads/release'
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: nightly
          files: |
            artifacts/cabal-audit
          fail_on_unmatched_files: true
